version: '3.8'

services:  
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - social_network_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: "postgresql://user:clave@localhost:5432/periferia?schema=public"
      JWT_SECRET: "mysecret"
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - social_network_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - social_network_network

volumes:
  postgres_data:

networks:
  social_network_network:
    driver: bridge